#!/bin/bash
gcloud run jobs deploy bestofbot-fnic --project=fnic-2024 --region=europe-west1 --source . --set-env-vars=BOTUSER="best_of_fnic_bot",BOTINSTANCE="lemmy.dbzer0.com",COMMUNITY="lemmydirectory@lemmy.dbzer0.com",COMMLIST="configs/_fnic_comms.json",IMAGES_ONLY=1,NSFW_BEHAVIOUR=2,POSTTITLE="💭 ❗Top Imaginary Network posts of the week❗ 💭" --set-secrets="BOTPW=best_of_fnic_bot:latest" &
gcloud run jobs deploy bestofbot-generalart --project=fnic-2024 --region=europe-west1 --source . --set-env-vars=BOTUSER="best_of_generalart_bot",BOTINSTANCE="lemmy.dbzer0.com",COMMUNITY="lemmydirectory@lemmy.dbzer0.com",COMMLIST="configs/_generalart_comms.json",IMAGES_ONLY=1,NSFW_BEHAVIOUR=2,POSTTITLE="🎨 ❗Top General Artworks posts of the week❗ 🎨" --set-secrets="BOTPW=best_of_generalart_bot:latest" &
gcloud run jobs deploy bestofbot-photo --project=fnic-2024 --region=europe-west1 --source . --set-env-vars=BOTUSER="best_of_photo_bot",BOTINSTANCE="lemmy.dbzer0.com",COMMUNITY="lemmydirectory@lemmy.dbzer0.com",COMMLIST="configs/_photography_comms.json",IMAGES_ONLY=1,NSFW_BEHAVIOUR=2,POSTTITLE="📷❗Top Photography posts of the week❗📷" --set-secrets="BOTPW=best_of_photo_bot:latest" &
gcloud run jobs deploy bestofbot-themes --project=fnic-2024 --region=europe-west1 --source . --set-env-vars=BOTUSER="best_of_themes_bot",BOTINSTANCE="lemmy.dbzer0.com",COMMUNITY="lemmydirectory@lemmy.dbzer0.com",COMMLIST="configs/_themes_comms.json",IMAGES_ONLY=1,NSFW_BEHAVIOUR=2,POSTTITLE="🖼️❗Top Themes posts of the week❗🖼️" --set-secrets="BOTPW=best_of_themes_bot:latest" &
gcloud run jobs deploy bestofbot-comics --project=fnic-2024 --region=europe-west1 --source . --set-env-vars=BOTUSER="best_of_comics_bot",BOTINSTANCE="lemmy.dbzer0.com",COMMUNITY="lemmydirectory@lemmy.dbzer0.com",COMMLIST="configs/_comics_comms.json",IMAGES_ONLY=1,NSFW_BEHAVIOUR=2,POSTTITLE="❗Top Comics posts of the week❗" --set-secrets="BOTPW=best_of_comics_bot:latest" &
gcloud run jobs deploy bestofbot-wallpapers --project=fnic-2024 --region=europe-west1 --source . --set-env-vars=BOTUSER="best_of_wallpapers_bot",BOTINSTANCE="lemmy.dbzer0.com",COMMUNITY="lemmydirectory@lemmy.dbzer0.com",COMMLIST="configs/_wallpaper_comms.json",IMAGES_ONLY=1,NSFW_BEHAVIOUR=2,POSTTITLE="❗Top Wallpaper posts of the week❗" --set-secrets="BOTPW=best_of_wallpaper_bot:latest" &
gcloud run jobs deploy bestofbot-anime --project=fnic-2024 --region=europe-west1 --source . --set-env-vars=BOTUSER="moebot",BOTINSTANCE="ani.social",COMMUNITY="lemmydirectory@lemmy.dbzer0.com",COMMLIST="configs/_anime_comms.json",IMAGES_ONLY=1,NSFW_BEHAVIOUR=1,POSTTITLE="💢❗Top Anime Art posts of the week❗💢" --set-secrets="BOTPW=moebot:latest"
wait
